<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\FoodFlow.BuildingBlocks.Authentication\FoodFlow.BuildingBlocks.Authentication.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\FoodFlow.BuildingBlocks.Infrastructure\FoodFlow.BuildingBlocks.Infrastructure.csproj" />
      <ProjectReference Include="..\FoodFlow.Modules.Identity.Domain\FoodFlow.Modules.Identity.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
